### ISSUE TITLE
No Dimming of groups

### ISSUE THREAD

**Issue by oktane83** [blocke/ha-local-echo#3]
This does not support dimming of groups.. I can only imagine this has something to do with ha-bridge by bwssytems having a bug that would not send the dim body content.. They have fixed this bug in the latest release of ha-bridge.. Any chance of getting that update into your code?

**Comment by blocke** [comment]
Sorry for the lack of response. If you haven't figured out already I've abandoned this project as what is now built into Home Assistant is far superior.
